
spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/soadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

quotes:
  base-url: http://localhost:8080/external

logging:
  level:
    org.springframework: INFO
    com.challenge.soa: DEBUG
